### ISSUE TITLE
Labs keeps freezing up when Ishtar restarts

### ISSUE THREAD

**Issue by designker** [aaronkennedy/ZingElements#389] opened 2015-11-03 18:15 UTC
While typing after awhile Labs starts to freeze up when Ishtar is building its UI.

**Comment by aaronkennedy** [comment] 2015-11-07 20:58
When this happens, does closing and reopening the simulator fix it?

**Comment by designker** [comment] 2015-11-07 21:12
Yes

**Comment by aaronkennedy** [comment] 2015-11-08 13:17
This is caused by leaks in the simulator agent. I am slowly fixing them. There is no real need for a general bug in this case.

**Closed by aaronkennedy** 2015-11-08 13:17 UTC
